#!/bin/bash

# IP监控脚本快速设置指南

echo "=== 🚀 IP监控脚本快速设置 ==="
echo ""

# 设置脚本权限
chmod +x /root/.openclaw/workspace/ip-monitor-bot.sh

echo "📋 设置步骤:"
echo ""
echo "1. 🔧 配置Telegram机器人:"
echo "   1.1 在Telegram中搜索 @BotFather"
echo "   1.2 发送 /newbot 创建新机器人"
echo "   1.3 设置机器人名称和用户名"
echo "   1.4 复制得到的Bot Token"
echo ""
echo "2. 📝 获取Chat ID:"
echo "   2.1 将机器人添加到你的聊天或频道"
echo "   2.2 发送任意消息给机器人"
echo "   2.3 访问: https://api.telegram.org/bot<你的Token>/getUpdates"
echo "   2.4 在JSON响应中找到 chat.id 字段"
echo ""
echo "3. ⚙️ 编辑脚本配置:"
echo "   编辑 /root/.openclaw/workspace/ip-monitor-bot.sh"
echo "   修改以下变量:"
echo "     TELEGRAM_BOT_TOKEN='你的Bot Token'"
echo "     TELEGRAM_CHAT_ID='你的Chat ID'"
echo ""
echo "4. 🧪 测试配置:"
echo "   /root/.openclaw/workspace/ip-monitor-bot.sh --test"
echo ""
echo "5. 🔄 安装服务:"
echo "   /root/.openclaw/workspace/ip-monitor-bot.sh --install"
echo ""
echo "6. 🚀 启动服务:"
echo "   systemctl daemon-reload"
echo "   systemctl enable ip-monitor.service"
echo "   systemctl start ip-monitor.service"
echo ""
echo "7. 📊 检查状态:"
echo "   /root/.openclaw/workspace/ip-monitor-bot.sh --status"
echo "   systemctl status ip-monitor.service"
echo ""
echo "=== ✅ 设置指南完成 ==="
echo ""
echo "💡 提示:"
echo "- 脚本会自动检测IP变化并推送Telegram通知"
echo "- 默认每5分钟检查一次IP"
echo "- 支持多个IP查询服务，确保可靠性"
echo "- 完整的日志记录和历史追踪"
echo ""
echo "📞 如有问题，我随时提供帮助！"